name: CMake

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-2019, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Configure CMake
      shell: bash
      run: |
        if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            cmake -B ${{github.workspace}}/build -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        else
            cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        fi
    - name: Build
      shell: bash
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}


#    - name: Test
#      working-directory: ${{github.workspace}}/build
#      shell: bash
#      run: ctest -C ${{env.BUILD_TYPE}}
